version: '3'
services:
  redis:
    image: redis
    container_name: redis
    volumes:
      - ./data:/data
      # - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./logs:/logs
    ports:
      - 6379:6379
    command: redis-server --port 6379 --requirepass redisroot@redisroot  --appendonly yes
