global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    # dashboards 10826
    static_configs:
      - targets: ['172.17.0.1:8090']

  - job_name: 'node'
    # dashboards 1860
    static_configs:
      - targets: ['172.17.0.1:9101']

  - job_name: 'mysql'
    # dashboards 7362
    static_configs:
      - targets: ['172.17.0.1:9104']

  - job_name: 'mongodb'
    # dashboards 7353
    static_configs:
      - targets: ['172.17.0.1:9216']
