version: '3'
services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      TZ: Asia/Shanghai
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio/
    command: server --console-address ':9001' /data  #指定容器中的目录 /data
    privileged: true