version: '3'
services:
  mysql:
    image: mysql:5.7.18
    container_name: mysql
    # restart: always
    volumes:
      - ./mysql/mydir:/mydir
      - ./mysql/datadir:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/my.cnf
      # 数据库还原目录 可将需要还原的sql文件放在这里
      - ./mysql/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=mysqlroot"
      - "MYSQL_DATABASE=mysqldb"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306