
version: '3'
services:
  mongodb:
    image: mongo:4
    container_name: mongodb
    volumes:
      - ./mongodb/db:/data/db
      - ./mongodb/log:/var/log/mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - TZ=Asia/Shanghai
